[package]
name = "codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
git2 = "0.20.2"
indoc = "2.0.6"
paste = "1.0.15"
rustfmt-wrapper = "0.2.1"
